app:
  name: "Event Manager"
  version: "1.0.0"
  debug: false
  log_level: "INFO"

database:
  type: "postgresql"  # Use PostgreSQL in production
  
  postgresql:
    host: "${PG_HOST}"
    port: "${PG_PORT}"
    database: "${PG_DATABASE}"
    username: "${PG_USERNAME}"
    password: "${PG_PASSWORD}"
    pool_size: 20
    max_overflow: 30

redis:
  url: "${REDIS_URL}"
  max_connections: 50

kafka:
  bootstrap_servers:
    - "${KAFKA_BOOTSTRAP_SERVERS}"
  group_id: "${KAFKA_GROUP_ID}"
  auto_offset_reset: "latest"

adapters:
  http:
    host: "0.0.0.0"
    port: 8000
    cors_enabled: false  # Disable CORS in production
  
  celery:
    worker_concurrency: 4
    task_time_limit: 600
    task_soft_time_limit: 540
  
  kafka:
    consumer_timeout_ms: 5000
    max_poll_records: 500

external_services:
  email:
    provider: "sendgrid"
    api_key: "${EMAIL_SERVICE_API_KEY}"
  
  payment_gateway:
    provider: "stripe"
    api_key: "${PAYMENT_GATEWAY_API_KEY}"
    url: "${PAYMENT_GATEWAY_URL}"

# Logging configuration
logging:
  file_rotation: "100 MB"
  file_retention: "30 days"
  level: "INFO"