# config/environments/production.yaml
app:
  name: "FastAPI Hexagonal"
  version: "1.0.0"
  debug: false
  log_level: "INFO"

database:
  type: "postgresql"
  pg_host: "${PG_HOST:localhost}"
  pg_port: "${PG_PORT:5432}"
  pg_database: "${PG_DATABASE:fastapi_hexagonal}"
  pg_username: "${PG_USERNAME:postgres}"
  pg_password: "${PG_PASSWORD:postgres}"
  pg_pool_size: 20

redis:
  url: "${REDIS_URL:redis://localhost:6379/0}"
  max_connections: 50

kafka:
  bootstrap_servers:
    - "${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
  group_id: "${KAFKA_GROUP_ID:fastapi-hexagonal}"
  auto_offset_reset: "latest"

external_services:
  email_service_api_key: "${EMAIL_SERVICE_API_KEY}"
  payment_gateway_api_key: "${PAYMENT_GATEWAY_API_KEY}"
  payment_gateway_url: "${PAYMENT_GATEWAY_URL}"
